### ISSUE TITLE
Support for conint, conlist and other constrained types

### ISSUE THREAD

**Issue by Fak3** [surenkov/django-pydantic-field#72]
If schema contains conint, the migrations fail with ValueError: Cannot serialize: Gt(gt=0)

```python
from django.db.models import Model
from django_pydantic_field import SchemaField
from pydantic import conint

class WebsiteUser(Model):
    test: conint(gt=0, lt=9999) = SchemaField(null=True)
```

Then on attempt to run makemigrations:
```
$ ./manage.py makemigrations
Migrations for 'example':
  example/migrations/0002_websiteuser_test.py
    - Add field test to websiteuser
Traceback (most recent call last):
  File "/home/z/pproj/django-hello-world/./manage.py", line 22, in <module>
    main()
  File "/home/z/pproj/django-hello-world/./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/z/pproj/django-hello-world/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
    ...
  File "/home/z/pproj/django-hello-world/.venv/lib/python3.10/site-packages/django_pydantic_field/compat/django.py", line 226, in serialize
    attr_repr, attr_imports = serializer_factory(attr).serialize()
  File "/home/z/pproj/django-hello-world/.venv/lib/python3.10/site-packages/django/db/migrations/serializer.py", line 42, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
  File "/home/z/pproj/django-hello-world/.venv/lib/python3.10/site-packages/django/db/migrations/serializer.py", line 201, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
  File "/home/z/pproj/django-hello-world/.venv/lib/python3.10/site-packages/django/db/migrations/serializer.py", line 378, in serializer_factory
    raise ValueError(
ValueError: Cannot serialize: Gt(gt=0)
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/4.1/topics/migrations/#migration-serializing
```

**Comment by quertenmont** [comment]
I am also having issues with StringConstraints
For instance my type is:
Annotated[str, pydantic.types.StringConstraints(pattern=r"[a-zA-Z0-9_]+")]

and when I try to make the migrations I get:

```
  File "/usr/local/lib/python3.11/site-packages/django_pydantic_field/compat/django.py", line 227, in serialize
    attr_repr, attr_imports = serializer_factory(attr).serialize()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/serializer.py", line 51, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django_pydantic_field/compat/django.py", line 227, in serialize
    attr_repr, attr_imports = serializer_factory(attr).serialize()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/serializer.py", line 51, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/serializer.py", line 229, in serialize
    item_string, item_imports = serializer_factory(item).serialize()
    ^^^^^^^^^^^^^^^^^^^^^^^^^

```

I print some debug at 
-   File "/usr/local/lib/python3.11/site-packages/django_pydantic_field/compat/django.py", line 227, in serialize
--> the value of attr is:  (<class 'str'>, StringConstraints(strip_whitespace=None, to_upper=None, to_lower=None, strict=None, min_length=None, max_length=None, pattern='[a-zA-Z0-9_]+'))

and later in 
-   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/serializer.py", line 229, in serialize
--> the value of item is: item pattern='[a-zA-Z0-9_]+'


Any idea how to solve this ?  Or at least move forward while keeping the constraints ?


Thanks in advance
Loic

**Comment by quertenmont** [comment]
In the meanwhile, here is the workaround that I've found (for those interested)
```
import sys
supportConstraints = False if sys.argv[1] == "makemigrations" else True

...

#defining my type that will be used in a django model later on
NonEmptyStr = (
    Annotated[str, StringConstraints(min_length=1)] if supportConstraints else str
)
```

This make the migration works, because django sees it as a normal str,
and it gives me at runTime the validation from pydantic through the serializers and forms,

it's a bit ugly, but it seems to work (so far...)

**Comment by surenkov** [comment]
@Fak3 @quertenmont thanks guys for looking into that, and please take my apologies for a long absence.

I've published the fix in `v0.5.1`, with backports in `v0.3.14` and `v0.4.2`.

Note though, that the fix is only applicable to Pydantic v2 installations: v1 does not provide a good way for detecting constrained types, building them ad-hoc. And in light of the fact that Pydantic v1 is in maintenance-only mode, and also #35 and #71, I don't see the support for its constraints worth an effort.

I'm going to resolve this issue, feel free to reopen it if necessary.
