### ISSUE TITLE
Got `TypeError: Object of type is not JSON serializable` when creating or bulk creating objects

### ISSUE THREAD

**Issue by miaow2** [surenkov/django-pydantic-field#73]
Hi! thanks for the great lib. 

After updating to pydantic v2 and adding new models with Schemafields I started getting the error `TypeError: Object of type is not JSON serializable` when creating objects

Models
```python
from django.db import models
from django_pydantic_field import SchemaField
from pydantic import BaseModel


class Node(BaseModel):
    name: str
    state: str


class Pool(models.Model):
    name = models.CharField(
        max_length=255,
    )
    nodes = SchemaField(
        schema=list[Node],
        default=list,
        blank=True,
    )
```

Traceback with save
```
>>> data = {'name': 'test', 'nodes': [{'name': 'node01', 'state': 'up'}, {'name': 'node02', 'state': 'up'}]}
>>> p = Pool(**data)
>>> p.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1819, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1743, in as_sql
    value_rows = [
                 ^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1744, in <listcomp>
    [
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1745, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1684, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/fields/json.py", line 134, in get_db_prep_save
    return self.get_db_prep_value(value, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/fields/json.py", line 129, in get_db_prep_value
    return connection.ops.adapt_json_value(value, self.encoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/backends/base/operations.py", line 584, in adapt_json_value
    return json.dumps(value, cls=encoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Node is not JSON serializable
```

Traceback with bulk_create
```
>>> data = {'name': 'test', 'nodes': [{'name': 'node01', 'state': 'up'}, {'name': 'node02', 'state': 'up'}]}
>>> p = Pool(**data)
>>> Pool.objects.bulk_create([p], batch_size=50)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/query.py", line 786, in bulk_create
    returned_columns = self._batched_insert(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/query.py", line 1831, in _batched_insert
    self._insert(
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1819, in execute_sql
    for sql, params in self.as_sql():
                       ^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1743, in as_sql
    value_rows = [
                 ^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1744, in <listcomp>
    [
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1745, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/sql/compiler.py", line 1684, in prepare_value
    return field.get_db_prep_save(value, connection=self.connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/fields/json.py", line 134, in get_db_prep_save
    return self.get_db_prep_value(value, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/models/fields/json.py", line 129, in get_db_prep_value
    return connection.ops.adapt_json_value(value, self.encoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/db/backends/base/operations.py", line 584, in adapt_json_value
    return json.dumps(value, cls=encoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/etc/venv/lib64/python3.11/site-packages/django/core/serializers/json.py", line 106, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Node is not JSON serializable
```

python3.11
Django==4.2
pydantic==2.9.2
django-pydantic-field==0.3.10

May be, my models or creating methods are incorrect, sorry for that.

**Comment by miaow2** [comment]
I've identified the root cause. The issue was related to the Django version, and it has been resolved in version 4.2.2. [commit](https://github.com/django/django/commit/9c301814b0d342bfc5f10c1513594ce5fbb6c6a9) link.

Sorry for the inconvenience!
